server:
  port: 9090
  error:
    include-message: always

spring:
  security:
    oauth2:
      client:
        provider:
          keycloak-gateway:
            issuer-uri: http://localhost:8080/realms/MariaEugeniaGiraldo

        registration:
          keycloak-gateway:
            client-id: api-gateway-client
            client-secret: qH5sJjvw46BCSX9NlUoZLKA0ziWxMvj6
            scope:
              - openid
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9090/login/oauth2/code/keycloak

  cloud:
    gateway:
      default-filters: TokenRelay
      routes:
        - id: ms-bills
          uri: http://localhost:8086
          predicates: Path=/bills/**

        - id: ms-users
          uri: http://localhost:8081
          predicates: Path=/users/**