spring:
  application:
    name: ms-users
  security:
    oauth2:
      client:
        registration:
          keycloak:
            realm: MariaEugeniaGiraldo
            server-url: http://localhost:8080
            client-id: authenticated_client_providers
            client-secret: Kk0TVaQxQF5nQNOJZ95eNyICmB0XMKDh
            authorization-grant-type: client_credentials
eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8081
  error:
    include-message: always
